name: Build & Test

on: 
  - push
  - pull_request

env:
  SOLUTION_FILE_PATH: ./DarkConfig.sln
  BUILD_CONFIGURATION: Debug

jobs:
  win32:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration:
          - Debug
          - Release
    env:
      BUILD_CONFIGURATION: ${{ matrix.configuration }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
 
      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

      - name: Install NUnit test runner
        run: nuget install NUnit.ConsoleRunner -Version 3.14.0 -OutputDirectory ./packages/

      - name: Run Unit Tests
        run: .\packages\NUnit.ConsoleRunner.3.14.0\tools\nunit3-console.exe .\test\bin\${{env.BUILD_CONFIGURATION}}\net48\DarkConfig.Tests.dll