name: Build

on: 
  - push
  - pull_request

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        dotnet-version: ['8.0']
        configuration:
          - Debug
          - Release

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build
        run: dotnet build --configuration ${{ matrix.configuration }}